import Link from "next/link";

export const metadata = { title: "Terms of Service | Rewind" };

const SECTIONS: { heading: string; body: string[] }[] = [
  {
    heading: "1. Acceptance of these terms",
    body: [
      "By accessing or using Rewind (the \"Service\"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.",
    ],
  },
  {
    heading: "2. What the Service is",
    body: [
      "Rewind is a free demonstration tool that visualizes and queries an AI agent's memory built with Cognee. It is provided for evaluation, education, and demonstration purposes only. It is not a production service and comes with no service level commitments of any kind.",
    ],
  },
  {
    heading: "3. AI-generated content",
    body: [
      "Answers shown in the Service are generated by a large language model from a knowledge graph of public GitHub data. They may be incomplete, outdated, or plainly wrong. They are not professional, legal, financial, medical, or any other kind of advice. You must not rely on them for any decision. You alone are responsible for anything you do with the output.",
    ],
  },
  {
    heading: "4. Acceptable use",
    body: [
      "You agree not to: (a) disrupt, overload, or attempt to gain unauthorized access to the Service or its infrastructure; (b) use the Service for any unlawful purpose; (c) attempt to extract secrets, bypass rate limits, or abuse the public endpoints; (d) scrape or automate requests at volumes that degrade the Service for others.",
      "We may rate-limit, block, or terminate access for any user at any time, with or without notice, for any reason, including suspected abuse.",
    ],
  },
  {
    heading: "5. Intellectual property",
    body: [
      "The Rewind source code is open source under the MIT License, available on GitHub. The demo dataset consists of public information from the Cognee open source repository, which remains subject to its own licenses and terms. \"Cognee\" and other third-party names are the property of their respective owners; their use here does not imply endorsement.",
    ],
  },
  {
    heading: "6. No warranty",
    body: [
      "THE SERVICE IS PROVIDED \"AS IS\" AND \"AS AVAILABLE\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AVAILABILITY, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE, OR THAT ANY OUTPUT WILL BE ACCURATE OR RELIABLE.",
    ],
  },
  {
    heading: "7. Limitation of liability",
    body: [
      "TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT SHALL THE OPERATOR OF REWIND BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, DATA, GOODWILL, OR BUSINESS, ARISING OUT OF OR IN CONNECTION WITH THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.",
      "BECAUSE THE SERVICE IS PROVIDED FREE OF CHARGE, OUR TOTAL AGGREGATE LIABILITY FOR ANY AND ALL CLAIMS RELATING TO THE SERVICE SHALL NOT EXCEED ZERO (0). SOME JURISDICTIONS DO NOT ALLOW CERTAIN EXCLUSIONS, SO PARTS OF THIS SECTION MAY NOT APPLY TO YOU; IN THAT CASE LIABILITY IS LIMITED TO THE SMALLEST AMOUNT PERMITTED BY LAW.",
    ],
  },
  {
    heading: "8. Indemnification",
    body: [
      "You agree to indemnify and hold harmless the operator of Rewind from any claims, damages, liabilities, and expenses (including reasonable legal fees) arising from your use of the Service or your violation of these terms.",
    ],
  },
  {
    heading: "9. Changes and termination",
    body: [
      "We may modify, suspend, or discontinue the Service, or update these terms, at any time without notice. The current terms will always be available at this page. Continued use after changes means you accept the updated terms.",
    ],
  },
  {
    heading: "10. Governing law",
    body: [
      "These terms are governed by the laws of India, without regard to conflict of law principles. Any disputes shall be subject to the exclusive jurisdiction of the courts of India.",
    ],
  },
  {
    heading: "11. Severability",
    body: [
      "If any provision of these terms is held unenforceable, the remaining provisions remain in full force and effect.",
    ],
  },
  {
    heading: "12. Contact",
    body: ["Questions about these terms: hello@divvsaxena.com."],
  },
];

export default function Terms() {
  return (
    <div className="min-h-screen bg-zinc-950 px-6 py-16 text-zinc-100">
      <div className="mx-auto max-w-2xl">
        <Link href="/" className="text-xs text-zinc-500 transition-colors hover:text-zinc-200">
          ← Back to Rewind
        </Link>
        <h1 className="mt-6 text-2xl font-semibold tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-xs text-zinc-500">Last updated: July 5, 2026</p>
        <div className="mt-8 flex flex-col gap-8">
          {SECTIONS.map((s) => (
            <section key={s.heading}>
              <h2 className="text-sm font-semibold text-zinc-100">{s.heading}</h2>
              <div className="mt-2 flex flex-col gap-3">
                {s.body.map((p) => (
                  <p key={p.slice(0, 40)} className="text-sm leading-relaxed text-zinc-400">
                    {p}
                  </p>
                ))}
              </div>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}
