import Link from "next/link";

export const metadata = { title: "Terms of Service | Rewind" };

export default function Terms() {
  return (
    <div className="min-h-screen bg-zinc-950 px-6 py-16 text-zinc-100">
      <div className="mx-auto max-w-2xl">
        <Link href="/" className="text-xs text-zinc-500 transition-colors hover:text-zinc-200">
          ← Back to Rewind
        </Link>
        <h1 className="mt-6 text-2xl font-semibold tracking-tight">Terms of Service</h1>
        <div className="mt-6 flex flex-col gap-4 text-sm leading-relaxed text-zinc-400">
          <p>
            Rewind is provided as is, free of charge, as a demonstration project. Use it at
            your own discretion.
          </p>
          <p>
            The demo dataset is public information from the Cognee GitHub repository.
            Answers are generated by a language model and may be inaccurate; do not rely on
            them for anything important.
          </p>
          <p>
            Please do not abuse the public endpoints. We may rate-limit or block traffic
            that disrupts the service.
          </p>
          <p>Contact: saxenadivv@gmail.com</p>
        </div>
      </div>
    </div>
  );
}
